language: python
python:
  - "3.6"
install:
  - python setup.py install
  - pip install pylint
  - gem install --no-document checkstyle_filter-git saddler saddler-reporter-github
  -
script:
  - echo ${TRAVIS_BRANCH}
  - ./review.sh
